version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "jikanwari-api-v2"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1mo5zn9ooi3kw"
s3_prefix = "jikanwari-api-v2"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
