on:
  push:
    branches:
      - master
name: cd
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.18
        id: go
      - name: Cache
        uses: actions/cache@v2.1.0
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
      - run: sam build
      - run: "sam deploy \
          --no-confirm-changeset \
          --no-fail-on-empty-changeset
          --parameter-overrides \
          DomainName=${{ secrets.DOMAIN_NAME }} \
          HostedZoneId=${{ secrets.HOSTED_ZONE_ID }} \
          CertificateArn=${{ secrets.CERTIFICATE_ARN }} 
          DynamoDBArn=${{ secrets.DYNAMODB_ARN }}"
