on:
  push:
name: ci
jobs:

  go-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.47.2

  go-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Up dynamodb
        run: docker-compose up -d dynamodb-local
        working-directory: local_resource
      - name: Copy aws config
        run: cp -r ./.aws ~/
        working-directory: local_resource
      - name: Create table
        run: sh create_table.sh
        working-directory: local_resource
      - name: Add dummy data
        run: sh add_dummy_data.sh
        working-directory: local_resource
      - name: Run test
        run: docker-compose run go-test
        working-directory: local_resource

  build-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: aws-actions/setup-sam@v1
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.18
        id: go
      - name: Cache
        uses: actions/cache@v2.1.0
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
      - name: build
        run: sam build
